# Generated by Django 4.1.5 on 2023-01-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
        ),
    ]
