# Generated by Django 4.1.5 on 2023-01-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
